# Generated by Django 5.2.9 on 2026-01-17 08:54

import django.db.models.deletion
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="分类名称")),
            ],
            options={
                "verbose_name": "案例分类",
                "verbose_name_plural": "案例分类",
            },
        ),
        migrations.CreateModel(
            name="CaseStudy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="课程标题")),
                ("description", models.TextField(blank=True, verbose_name="课程简介")),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="covers/",
                        verbose_name="封面图",
                    ),
                ),
                (
                    "view_count",
                    models.PositiveIntegerField(default=0, verbose_name="浏览量"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="发布时间"),
                ),
                ("content", models.TextField(blank=True, verbose_name="导读/详情")),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cases",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="负责教师",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="common.category",
                        verbose_name="所属分类",
                    ),
                ),
            ],
            options={
                "verbose_name": "思政课程",
                "verbose_name_plural": "思政课程",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CaseChapter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="章节标题")),
                (
                    "chapter_type",
                    models.CharField(
                        choices=[
                            ("video", "📺 视频学习"),
                            ("text", "📄 图文阅读"),
                            ("file", "💾 资料下载"),
                        ],
                        default="video",
                        max_length=10,
                        verbose_name="章节类型",
                    ),
                ),
                (
                    "content_format",
                    models.CharField(
                        choices=[("rich", "🌈 富文本"), ("md", "📝 Markdown")],
                        default="rich",
                        max_length=10,
                        verbose_name="排版模式",
                    ),
                ),
                (
                    "font_size",
                    models.CharField(
                        choices=[
                            ("14px", "小号"),
                            ("16px", "标准"),
                            ("18px", "中号"),
                            ("20px", "大号"),
                        ],
                        default="16px",
                        max_length=10,
                        verbose_name="字体大小",
                    ),
                ),
                (
                    "content_rich",
                    django_ckeditor_5.fields.CKEditor5Field(
                        blank=True, null=True, verbose_name="富文本编辑器"
                    ),
                ),
                (
                    "content_md",
                    models.TextField(
                        blank=True, null=True, verbose_name="Markdown编辑器"
                    ),
                ),
                (
                    "video_file",
                    models.FileField(
                        blank=True,
                        upload_to="videos/chapters/",
                        verbose_name="视频文件",
                    ),
                ),
                ("video_url", models.URLField(blank=True, verbose_name="外部视频链接")),
                (
                    "attachment",
                    models.FileField(
                        blank=True, upload_to="attachments/", verbose_name="课件资料"
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="排序")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chapters",
                        to="common.casestudy",
                        verbose_name="所属课程",
                    ),
                ),
            ],
            options={
                "verbose_name": "课程章节",
                "verbose_name_plural": "课程章节",
                "ordering": ["order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(verbose_name="评论内容")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="common.casestudy",
                        verbose_name="所属案例",
                    ),
                ),
                (
                    "chapter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="chapter_comments",
                        to="common.casechapter",
                    ),
                ),
                (
                    "likes",
                    models.ManyToManyField(
                        blank=True,
                        related_name="liked_comments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="点赞用户",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "互动评论",
                "verbose_name_plural": "互动评论",
            },
        ),
        migrations.CreateModel(
            name="Note",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(verbose_name="笔记内容")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="common.casestudy",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "学习笔记",
                "verbose_name_plural": "学习笔记",
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "普通管理员"),
                            ("teacher", "教师"),
                            ("student", "学生"),
                        ],
                        default="student",
                        max_length=10,
                        verbose_name="角色",
                    ),
                ),
                (
                    "student_id",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="学号/工号"
                    ),
                ),
                (
                    "is_banned",
                    models.BooleanField(default=False, verbose_name="是否封禁"),
                ),
                (
                    "ban_reason",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="封禁理由"
                    ),
                ),
                (
                    "ban_end_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="解封时间"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "用户档案",
                "verbose_name_plural": "用户档案",
            },
        ),
        migrations.CreateModel(
            name="Favorite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="common.casestudy",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "case")},
            },
        ),
    ]
