# Generated by Django 5.2.9 on 2026-01-18 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="casechapter",
            name="resource_link",
            field=models.URLField(
                blank=True,
                help_text="当选择【资料下载】时，可在此填入网盘或外部下载地址",
                null=True,
                verbose_name="外部资料链接",
            ),
        ),
    ]
