# Generated by Django 5.2.9 on 2026-01-20 09:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0002_casechapter_resource_link"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="casechapter",
            name="chapter_type",
            field=models.CharField(
                choices=[
                    ("video", "📺 视频学习"),
                    ("text", "📄 图文阅读"),
                    ("file", "💾 外部案例资料"),
                ],
                default="video",
                max_length=10,
                verbose_name="章节类型",
            ),
        ),
        migrations.AlterField(
            model_name="casechapter",
            name="resource_link",
            field=models.URLField(
                blank=True,
                help_text="当选择【外部案例资料】时，可在此填入网盘或外部下载地址",
                null=True,
                verbose_name="外部资料链接",
            ),
        ),
        migrations.CreateModel(
            name="StudyRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "view_duration",
                    models.PositiveIntegerField(default=0, verbose_name="学习时长(秒)"),
                ),
                (
                    "last_updated",
                    models.DateTimeField(auto_now=True, verbose_name="最后更新时间"),
                ),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="study_records",
                        to="common.casestudy",
                        verbose_name="所属课程",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "学情记录",
                "verbose_name_plural": "学情记录",
                "unique_together": {("user", "case")},
            },
        ),
    ]
