# Generated by Django 5.2.9 on 2026-02-13 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0003_alter_casechapter_chapter_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="studyrecord",
            name="last_chapter",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="common.casechapter",
                verbose_name="最近学习章节",
            ),
        ),
    ]
