# Generated by Django 5.2.9 on 2026-02-14 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0004_studyrecord_last_chapter"),
    ]

    operations = [
        migrations.CreateModel(
            name="BranchNode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "trigger_time",
                    models.IntegerField(
                        help_text="例如：视频播放到第15秒弹出选项，填 15",
                        verbose_name="触发时间(秒)",
                    ),
                ),
                (
                    "question",
                    models.CharField(max_length=255, verbose_name="弹出的问题"),
                ),
                (
                    "chapter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="branch_nodes",
                        to="common.casechapter",
                        verbose_name="所属视频章节",
                    ),
                ),
            ],
            options={
                "verbose_name": "视频交互节点",
                "verbose_name_plural": "视频交互节点",
            },
        ),
        migrations.CreateModel(
            name="BranchOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text",
                    models.CharField(
                        help_text="例如：选择A", max_length=100, verbose_name="选项文本"
                    ),
                ),
                (
                    "jump_to",
                    models.IntegerField(
                        help_text="例如：选择该项后跳转到第60秒，填 60",
                        verbose_name="跳转到(秒)",
                    ),
                ),
                (
                    "node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="common.branchnode",
                        verbose_name="所属节点",
                    ),
                ),
            ],
            options={
                "verbose_name": "交互选项",
                "verbose_name_plural": "交互选项",
            },
        ),
    ]
