# Generated by Django 5.2.9 on 2026-02-14 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0005_branchnode_branchoption"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="branchoption",
            name="jump_to",
        ),
        migrations.AddField(
            model_name="branchoption",
            name="feedback",
            field=models.TextField(
                blank=True,
                help_text="学生选择该项后，弹出的反馈内容",
                null=True,
                verbose_name="选择后的解析/回答",
            ),
        ),
    ]
