# Generated by Django 5.2.9 on 2026-02-16 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0006_remove_branchoption_jump_to_branchoption_feedback"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="chapter",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="common.casechapter",
                verbose_name="所属章节",
            ),
        ),
    ]
